# Generated by Django 2.2.6 on 2019-10-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='brithdate',
            new_name='birthdate',
        ),
    ]
